apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    cluster-group: prod-1
    cluster-name: prod-1-cluster
    owner: platforms-team
    type: production
  name: prod-1-cluster
  namespace: kcc
spec:
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    kalmConfig:
      enabled: true
  clusterIpv4Cidr: 10.96.0.0/14
  description: Shared workload cluster meant for production workloads
  initialNodeCount: 3
  location: us-central1-a
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 10.2.0.0/16
      displayName: Trusted external network
  networkingMode: ROUTES
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    cluster-group: prod-1
    cluster-name: prod-1-cluster
    owner: platforms-team
    type: production
  name: prod-1-gkehubmembership
  namespace: kcc
spec:
  authority:
    issuer: https://container.googleapis.com/v1/projects/vishnuk-cloud/locations/us-central1-a/clusters/prod-1-cluster
  description: A sample GKE Hub membership
  endpoint:
    gkeCluster:
      resourceRef:
        name: prod-1cluster
  location: global
