apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    cluster-name: prod-1
    cluster-type: production
    owner: platforms-team
    type: production
  name: prod-1-cluster
  namespace: kcc
spec:
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    kalmConfig:
      enabled: true
  clusterIpv4Cidr: 10.96.0.0/14
  description: Shared workload cluster meant for production workloads
  initialNodeCount: 3
  location: us-central1-a
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 10.2.0.0/16
      displayName: Trusted external network
  networkingMode: ROUTES
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
