apiVersion: v1
kind: Namespace
metadata:
  annotations: cnrm.cloud.google.com/project-id=vishnuk-cloud
  labels:
    owner: platforms-team
  name: infra-resources-kcc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    owner: platforms-team
  name: infra-resources-app
  namespace: argocd
spec:
  destination:
    namespace: kcc
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
  project: admin-project
  source:
    directory:
      recurse: true
    path: argo/admin-cluster
    repoURL: https://github.com/vishh/argocd-anthos-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
