apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    owner: platforms-team
    type: production
  name: prod-2-containercluster-vpcnative
  namespace: kcc
spec:
  ipCidrRange: 10.5.0.0/16
  networkRef:
    name: containercluster-vpcnative
  region: us-central1
  secondaryIpRange:
  - ipCidrRange: 10.6.0.0/16
    rangeName: servicesrange
  - ipCidrRange: 10.7.0.0/16
    rangeName: clusterrange
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    availability: high
    cluster-name: prod-2
    cluster-type: production
    owner: platforms-team
    target-audience: production
    type: production
  name: prod-2-cluster
  namespace: kcc
spec:
  addonsConfig:
    configConnectorConfig:
      enabled: true
    dnsCacheConfig:
      enabled: true
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: true
    resourceLimits:
    - maximum: 100
      minimum: 10
      resourceType: cpu
    - maximum: 1000
      minimum: 100
      resourceType: memory
  defaultMaxPodsPerNode: 100
  description: Shared workload cluster meant for production workloads
  enableBinaryAuthorization: true
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: clusterrange
    servicesSecondaryRangeName: servicesrange
  location: us-central1
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "00:00"
  networkPolicy:
    enabled: true
  networkRef:
    name: containercluster-vpcnative
  networkingMode: VPC_NATIVE
  nodeLocations:
  - us-central1-a
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: containercluster-vpcnative
  podSecurityPolicyConfig:
    enabled: true
  releaseChannel:
    channel: STABLE
  subnetworkRef:
    name: prod-2-containercluster-vpcnative
  verticalPodAutoscaling:
    enabled: true
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
