apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    cluster-group: prod
    cluster-name: prod-2-cluster
    owner: platforms-team
    type: production
  name: prod-2-cluster
  namespace: kcc
spec:
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    kalmConfig:
      enabled: true
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: true
    resourceLimits:
    - maximum: 100
      minimum: 10
      resourceType: cpu
    - maximum: 1000
      minimum: 100
      resourceType: memory
  clusterIpv4Cidr: 10.92.0.0/14
  description: Shared workload cluster meant for production workloads
  initialNodeCount: 3
  location: us-central1-a
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 10.3.0.0/16
      displayName: Trusted external network
  networkingMode: ROUTES
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    cluster-group: prod
    cluster-name: prod-2-cluster
    owner: platforms-team
    type: production
  name: prod-2-gkehubmembership
  namespace: kcc
spec:
  authority:
    issuer: https://container.googleapis.com/v1/projects/vishnuk-cloud/locations/us-central1-a/clusters/prod-2-cluster
  description: Production GKE cluster prod-2-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: prod-2-cluster
  location: global
