apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    cluster-group: staging
    cluster-name: staging-1-cluster
    owner: platforms-team
    type: production
  name: staging-1-cluster
  namespace: kcc
spec:
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    kalmConfig:
      enabled: true
  clusterIpv4Cidr: 10.98.0.0/14
  description: Shared workload cluster meant for production workloads
  initialNodeCount: 3
  location: us-central1-a
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 10.4.0.0/16
      displayName: Trusted external network
  networkingMode: ROUTES
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    cluster-group: staging
    cluster-name: staging-1-cluster
    owner: platforms-team
    type: production
  name: staging-1-gkehubmembership
  namespace: kcc
spec:
  authority:
    issuer: https://container.googleapis.com/v1/projects/vishnuk-cloud/locations/us-central1-a/clusters/staging-1-cluster
  description: Registering GKE cluster prod-2-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: staging-1-cluster
  location: global
