apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    owner: platforms-team
    type: staging
  name: staging-1-containercluster-dep-vpcnative
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    owner: platforms-team
    type: staging
  name: staging-1-containercluster-dep-vpcnative
spec:
  ipCidrRange: 10.8.0.0/16
  networkRef:
    name: containercluster-dep-vpcnative
  region: us-central1
  secondaryIpRange:
  - ipCidrRange: 10.9.0.0/16
    rangeName: servicesrange
  - ipCidrRange: 10.10.0.0/16
    rangeName: clusterrange
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    availability: high
    cluster-name: staging-1
    cluster-type: staging
    owner: platforms-team
    target-audience: production
    type: staging
  name: staging-1-cluster
spec:
  addonsConfig:
    configConnectorConfig:
      enabled: true
    dnsCacheConfig:
      enabled: true
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: true
    resourceLimits:
    - maximum: 100
      minimum: 10
      resourceType: cpu
    - maximum: 1000
      minimum: 100
      resourceType: memory
  defaultMaxPodsPerNode: 100
  description: Shared workload cluster meant for staging workloads
  enableBinaryAuthorization: true
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: clusterrange
    servicesSecondaryRangeName: servicesrange
  location: us-central1
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "00:00"
  networkPolicy:
    enabled: true
  networkRef:
    name: containercluster-dep-vpcnative
  networkingMode: VPC_NATIVE
  nodeLocations:
  - us-central1-a
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: containercluster-dep-vpcnative
  podSecurityPolicyConfig:
    enabled: true
  releaseChannel:
    channel: STABLE
  subnetworkRef:
    name: staging-1-containercluster-dep-vpcnative
  verticalPodAutoscaling:
    enabled: true
  workloadIdentityConfig:
    identityNamespace: vishnuk-cloud.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  labels:
    cluster-name: staging-1
    cluster-type: staging
    owner: platforms-team
    type: staging
  name: staging-1-gkehubmembership
spec:
  authority:
    issuer: https://container.googleapis.com/v1/projects/vishnuk-cloud/locations/us-central1/clusters/staging-1-cluster
  description: Registering GKE cluster prod-2-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: staging-1-cluster
  location: global
