apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: admin-cluster
  labels:
    owner: platforms-team
  name: argocd-connect-gateway-iampolicy
  namespace: kcc
spec:
  bindings:
  - members:
    - serviceAccount:vishnuk-cloud.svc.id.goog[argocd/argocd-application-controller]
    role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: connect-gateway
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: admin-cluster
  labels:
    owner: platforms-team
  name: connect-gateway-iampolicy
  namespace: kcc
spec:
  bindings:
  - members:
    - serviceAccount:connect-gateway@vishnuk-cloud.iam.gserviceaccount.com
    role: roles/gkehub.gatewayAdmin
  - members:
    - serviceAccount:connect-gateway@vishnuk-cloud.iam.gserviceaccount.com
    role: roles/gkehub.viewer
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: connect-gateway
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: admin-cluster
  labels:
    owner: platforms-team
  name: connect-gateway
  namespace: kcc
spec:
  displayName: GKE Connect Gateway
