apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: admin-
namespace: argocd
commonLabels:
  owner: platforms-team
commonAnnotations:
  configsync.gke.io/cluster-name-selector: admin
  
bases:
- ../../../../base/argo-app
- ../../../../base/argo-project

patchesStrategicMerge:
- admin-project.yaml
- admin-app.yaml
