apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  # Project description
  description: ArgoCD project that will bootstrap ArgoCD to pull configs from an admin git repo.

  sourceRepos:
  - "git@github.com:vishh/argocd-anthos-demo.git"

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

