apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcc

commonLabels:
  owner: platforms-team

commonAnnotations:
  configsync.gke.io/cluster-name-selector: admin

resources:
- identity.yaml
