apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcc

commonLabels:
  owner: platforms-team

commonAnnotations:
  configmanagement.gke.io/cluster-selector: admin-cluster

resources:
- identity.yaml
