apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-1-
namespace: kcc

commonLabels:
  owner: platforms-team
  type: production
  cluster-name: prod-1-cluster
  cluster-group: prod-1
  
bases:
- ../../../../../base/gke-cluster/

patchesStrategicMerge:
- cluster.yaml
