apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: admin-infra-policy-
commonLabels:
  owner: platforms-team
  
bases:
- ../../../../../base/argo-app

patchesStrategicMerge:
- infra-app.yaml
