apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  repositories: |
    - url: git@github.com:vishh/argocd-anthos-demo.git
      sshPrivateKeySecret:
        name: git-creds
        key: sshPrivateKey
    
