apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  owner: platforms-team
commonAnnotations:
  configsync.gke.io/cluster-selector: admin-cluster

resources:
- install.yaml
- configmap.yaml
- rbac.yaml
- namespace.yaml
- cluster-rbac.yaml
- crds.yaml

