apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  # The project the application belongs to.
  project: admin-project

  # Source of the application manifests
  source:
    repoURL: https://github.com/vishh/argocd-anthos-demo
    targetRevision: HEAD
    path: argo

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
 