apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-2-
namespace: kcc

commonLabels:
  owner: platforms-team
  type: production
  
bases:
- ../../../../../base/gke-cluster/

patchesStrategicMerge:
- compute-subnetwork.yaml
- cluster.yaml
