apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcc
namePrefix: staging-1-

commonLabels:
  owner: platforms-team
  type: production
  cluster-name: staging-1-cluster
  cluster-group: staging
  
bases:
- ../../../../../base/gke-cluster/

patchesStrategicMerge:
- cluster.yaml

