apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kcc

commonLabels:
  owner: platforms-team
  type: production
  cluster-name: staging-1-cluster
  cluster-group: staging
  
bases:
- ../../../../../base/gke-cluster/

patchesStrategicMerge:
- cluster.yaml

patchesJson6902:
  - target:
      group: gkehub.cnrm.cloud.google.com
      version: v1beta1
      kind: GKEHubMembership 
      name: gkehubmembership
    path: hub-membership-name-patch.yaml
  - target:
      group: container.cnrm.cloud.google.com
      version: v1beta1
      kind: ContainerCluster
      name: cluster
    path: cluster-name.yaml
    
